
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/ST/STM32CubeCLT_1.19.0/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:37 (project)"
    message: |
      The target system is: Linux -  - loongson
      The host system is: Windows - 10.0.26200 - AMD64
...
